name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  ci-data:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.fetch.outputs.result }}
    steps:
      - id: fetch
        uses: oxidize-rb/actions/fetch-ci-data@ec90b4aa48795518d79be3f5cc478d1d7ccd02a8 # v1.5.0
        with:
          stable-ruby-versions: |
            # Explicitly include all Ruby versions we want to support
            # to ensure binaries are built for each version
            only: ['3.3', '3.4', '4.0']
  rspec:
    runs-on: ${{ matrix.os }}
    needs: ci-data
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        ruby: ${{ fromJSON(needs.ci-data.outputs.result).stable-ruby-versions }}
        rust: ["stable"]
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: oxidize-rb/actions/setup-ruby-and-rust@ec90b4aa48795518d79be3f5cc478d1d7ccd02a8 # v1.5.0
        with:
          ruby-version: ${{ matrix.ruby }}
          rustup-toolchain: ${{ matrix.rust }}
          bundler-cache: true
          cargo-cache: false
      - name: Run ruby tests
        run: bundle exec rake
      - name: Compile rust ext
        run: bundle exec rake compile:release

  rspec_ruby_version_file:
    name: "RSpec (ruby-version-file)"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: oxidize-rb/actions/setup-ruby-and-rust@ec90b4aa48795518d79be3f5cc478d1d7ccd02a8 # v1.5.0
        with:
          rustup-toolchain: stable
          bundler-cache: true
          cargo-cache: false
      - name: Run ruby tests
        run: bundle exec rake
      - name: Compile rust ext
        run: bundle exec rake compile:release
  static_type_check:
    name: "Type Check"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@14594264cd68ce8a2345dd349bc3d138a4ef85c8 # v1.327.0
        with:
          bundler-cache: true
      - name: Run static type checks
        run: bundle exec srb tc
  notify_on_failure:
    runs-on: ubuntu-latest
    needs: [rspec, static_type_check]
    if: ${{ failure() && github.ref == 'refs/heads/main' }}
    steps:
      - uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "${{ github.repository }}/${{ github.ref }}: FAILED\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
